swagger: '2.0'
info:
  title: API Géo
  version: '1.1'
host: geo.api.gouv.fr
schemes:
  - https
produces:
  - application/json
parameters:
  communeFieldsParam:
    name: fields
    in: query
    description: Liste des champs souhaités dans la réponse
    type: array
    items:
      type: string
      enum:
        - nom
        - code
        - codesPostaux
        - centre
        - surface
        - contour
        - mairie
        - bbox
        - codeEpci
        - epci
        - codeDepartement
        - departement
        - codeRegion
        - region
        - population
    collectionFormat: csv
    default:
      - nom
      - code
      - codesPostaux
      - codeEpci
      - codeDepartement
      - codeRegion
      - population
  epciFieldsParam:
    name: fields
    in: query
    description: Liste des champs souhaités dans la réponse
    type: array
    items:
      type: string
      enum:
        - nom
        - code
        - population
        - financement
        - type
        - codesRegions
        - codesDepartements
        - zone
        - centre
        - surface
        - contour
        - bbox
    collectionFormat: csv
    default:
      - nom
      - code
      - codesRegions
      - codesDepartements
  departementFieldsParam:
    name: fields
    in: query
    description: Liste des champs souhaités dans la réponse
    type: array
    items:
      type: string
      enum:
        - nom
        - code
        - codeRegion
        - region
    collectionFormat: csv
    default:
      - nom
      - code
      - codeRegion
  regionFieldsParam:
    name: fields
    in: query
    description: Liste des champs souhaités dans la réponse
    type: array
    items:
      type: string
      enum:
        - nom
        - code
    collectionFormat: csv
    default:
      - nom
      - code
  formatParam:
    name: format
    in: query
    description: Format de réponse attendu
    type: string
    enum: ['json', 'geojson']
    default: json
  communeGeometryParam:
    name: geometry
    in: query
    description: Géométrie à utiliser pour la sortie géographique
    type: string
    enum: ['centre', 'contour', 'mairie', 'bbox']
    default: centre
  epciGeometryParam:
    name: geometry
    in: query
    description: Géométrie à utiliser pour la sortie géographique
    type: string
    enum: ['centre', 'contour', 'bbox']
    default: centre
  limitParam:
    name: limit
    in: query
    description: Nombre d'éléments à retourner
    type: integer
    format: int32
    default: 0
paths:
  /communes:
    get:
      summary: Recherche des communes
      tags:
        - Communes
      parameters:
        - name: codePostal
          in: query
          description: Code postal associé
          type: string
        - name: lat
          in: query
          description: Latitude (en degrés)
          type: number
          format: float
        - name: lon
          in: query
          description: Longitude (en degrés)
          type: number
          format: float
        - name: nom
          in: query
          description: Nom de la commune
          type: string
        - name: boost
          in: query
          description: Mode de boost de la recherche par nom
          type: string
        - name: code
          in: query
          description: Code de la commune
          type: string
        - name: codeEpci
          in: query
          description: Code de l'EPCI associé
          type: string
        - name: codeDepartement
          in: query
          description: Code du département associé
          type: string
        - name: codeRegion
          in: query
          description: Code de la région associée
          type: string
        - $ref: '#/parameters/communeFieldsParam'
        - $ref: '#/parameters/formatParam'
        - $ref: '#/parameters/communeGeometryParam'
      responses:
        200:
          description: Liste de communes
          schema:
            type: array
            items:
              $ref: '#/definitions/Commune'
        400:
          description: Erreur. Requête mal formée
          schema:
            $ref: '#/definitions/Error'


  /communes/{code}:
    get:
      summary: Récupérer les informations concernant une commune
      tags:
        - Communes
      parameters:
        - name: code
          in: path
          description: Code INSEE de la commune
          required: true
          type: string
        - $ref: '#/parameters/communeFieldsParam'
        - $ref: '#/parameters/formatParam'
        - $ref: '#/parameters/communeGeometryParam'
      responses:
        200:
          description: Informations concernant une commune
          schema:
            $ref: '#/definitions/Commune'
        400:
          description: Erreur. Requête mal formée
          schema:
            $ref: '#/definitions/Error'
        404:
          description: Commune introuvable
          schema:
            $ref: '#/definitions/Error'
  /epci:
    get:
      summary: Recherche des EPCI
      tags:
        - Communes
        - EPCI
      parameters:
        - name: nom
          in: query
          description: Nom de l'EPCI
          type: string
        - name: boost
          in: query
          description: Mode de boost de la recherche par nom
          type: string
        - name: codeEpci
          in: query
          description: Code de l'EPCI associé
          type: string
        - name: codeDepartement
          in: query
          description: Code du département associé
          type: string
        - name: codeRegion
          in: query
          description: Code de la région associée
          type: string
        - $ref: '#/parameters/epciFieldsParam'
        - $ref: '#/parameters/formatParam'
        - $ref: '#/parameters/epciGeometryParam'
      responses:
        200:
          description: Liste des EPCI
          schema:
            type: array
            items:
              $ref: '#/definitions/Epci'
        400:
          description: Erreur. Requête mal formée
          schema:
            $ref: '#/definitions/Error'
  /epci/{code}:
    get:
      summary: Récupérer les informations concernant un EPCI
      tags:
        - EPCI
      parameters:
        - name: code
          in: path
          description: Code INSEE de la commune
          required: true
          type: string
        - $ref: '#/parameters/epciFieldsParam'
        - $ref: '#/parameters/formatParam'
        - $ref: '#/parameters/epciGeometryParam'
      responses:
        '200':
          description: Informations concernant une commune
          schema:
            $ref: '#/definitions/Epci'
        400:
          description: Erreur. Requête mal formée
          schema:
            $ref: '#/definitions/Error'
        404:
          description: EPCI introuvable
          schema:
            $ref: '#/definitions/Error'
  /epci/{code}/communes:
    get:
      summary: Renvoi les communes d'un EPCI
      tags:
        - EPCI
        - Communes
      parameters:
        - name: code
          in: path
          description: Code de l'EPCI
          required: true
          type: string
        - $ref: '#/parameters/communeFieldsParam'
        - $ref: '#/parameters/formatParam'
        - $ref: '#/parameters/communeGeometryParam'
      responses:
        200:
          description: Liste des communes de l'EPCI
          schema:
            type: array
            items:
              $ref: '#/definitions/Commune'
        400:
          description: Erreur. Requête mal formée
          schema:
            $ref: '#/definitions/Error'
        404:
          description: EPCI introuvable
          schema:
            $ref: '#/definitions/Error'

  /departements:
      get:
        summary: Recherche des départements
        tags:
          - Départements
        parameters:
          - name: code
            in: query
            description: Code du département
            type: string
          - name: codeRegion
            in: query
            description: Code région associé
            type: string
          - name: nom
            in: query
            description: Nom du département
            type: string
          - $ref: '#/parameters/departementFieldsParam'
        responses:
          200:
            description: Le ou les départements
            schema:
              type: array
              items:
                $ref: '#/definitions/Departement'
          400:
            description: Erreur. Requête mal formée
            schema:
              $ref: '#/definitions/Error'

  /departements/{code}:
    get:
      summary: Récupérer les informations concernant un département
      tags:
        - Départements
      parameters:
        - name: code
          in: path
          description: Code du département
          required: true
          type: string
        - $ref: '#/parameters/departementFieldsParam'
      responses:
        200:
          description: Informations concernant un département
          schema:
            $ref: '#/definitions/Departement'
        400:
          description: Erreur. Requête mal formée
          schema:
            $ref: '#/definitions/Error'
        404:
          description: Département introuvable
          schema:
            $ref: '#/definitions/Error'

  /departements/{code}/communes:
    get:
      summary: Renvoi les communes d'un département
      tags:
        - Départements
        - Communes
      parameters:
        - name: code
          in: path
          description: Code du département
          required: true
          type: string
        - $ref: '#/parameters/communeFieldsParam'
        - $ref: '#/parameters/formatParam'
        - $ref: '#/parameters/communeGeometryParam'
      responses:
        200:
          description: Liste des communes du département
          schema:
            type: array
            items:
              $ref: '#/definitions/Commune'
        400:
          description: Erreur. Requête mal formée
          schema:
            $ref: '#/definitions/Error'
        404:
          description: Département introuvable
          schema:
            $ref: '#/definitions/Error'

  /regions:
      get:
        summary: Recherche des régions
        tags:
          - Régions
        parameters:
          - name: code
            in: query
            description: Code de la région
            type: string
          - name: nom
            in: query
            description: Nom de la région
            type: string
          - $ref: '#/parameters/regionFieldsParam'
        responses:
          200:
            description: La ou les régions
            schema:
              type: array
              items:
                $ref: '#/definitions/Region'
          400:
            description: Erreur. Requête mal formée
            schema:
              $ref: '#/definitions/Error'

  /regions/{code}:
    get:
      summary: Récupérer les informations concernant une région
      tags:
        - Régions
      parameters:
        - name: code
          in: path
          description: Code de la région
          required: true
          type: string
        - $ref: '#/parameters/regionFieldsParam'
      responses:
        200:
          description: Informations concernant la région
          schema:
            $ref: '#/definitions/Region'
        400:
          description: Erreur. Requête mal formée
          schema:
            $ref: '#/definitions/Error'
        404:
          description: Région introuvable
          schema:
            $ref: '#/definitions/Error'

  /regions/{code}/departements:
    get:
      summary: Renvoi les départements d'une région
      tags:
        - Départements
        - Régions
      parameters:
        - name: code
          in: path
          description: Code de la région
          required: true
          type: string
        - $ref: '#/parameters/regionFieldsParam'
      responses:
        200:
          description: Liste des départements de la région
          schema:
            type: array
            items:
              $ref: '#/definitions/Departement'
        400:
          description: Erreur. Requête mal formée
          schema:
            $ref: '#/definitions/Error'
        404:
          description: Département introuvable
          schema:
            $ref: '#/definitions/Error'

definitions:
  Error:
    type: object
    properties:
      code:
        type: integer
        description: Code HTTP de l'erreur
      message:
        type: string
        description: Libellé de l'erreur
      description:
        type: string
        description: Explication
  Commune:
    type: object
    properties:
      code:
        type: string
        description: Code INSEE de la commune
      nom:
        type: string
        description: Nom de la commune
      codesPostaux:
        type: array
        description: Liste des codes postaux associés à la commune
        items:
          type: string
      codeEpci:
        type: string
        description: Code de l'EPCI associé à la commune
      codeDepartement:
        type: string
        description: Code du département associé à la commune
      codeRegion:
        type: string
        description: Code de la région associée à la commune
      epci:
        $ref: '#/definitions/Epci'
      departement:
        $ref: '#/definitions/Departement'
      region:
        $ref: '#/definitions/Region'
      population:
        type: integer
        description: Population municipale
      surface:
        type: number
        format: float
        description: Surface de la commune, en hectares
      centre:
        type: object
        description: Centre de la commune (Point GeoJSON)
      contour:
        type: object
        description: Contour de la commune (Polygon GeoJSON)
      mairie:
        type: object
        description: Mairie principale de la commune (Point GeoJSON). Pour les COM et les communes mortes pour la France, on retourne le centre.
      bbox:
        type: object
        description: Rectangle englobant la commune (Polygon GeoJSON)
  Epci:
    type: object
    properties:
      code:
        type: string
        description: Code SIREN de l'EPCI
      nom:
        type: string
        description: Nom de l'EPCI
      type:
        type: string
        description: Type de l'EPCI, soit communauté d'agglomération (CA), soit communauté de communes (CC), soit communauté urbaine (CU), soit métropole de Lyon (MET69), soit métropole (METRO)
      financement:
        type: string
        description: Financement de l'EPCI, soit fiscalité additionnelle (FA), soit en fiscalité professionnelle unique (FPU)
      codesDepartements:
        type: array
        description: Liste des départements de l'EPCI
        items:
          type: string
      codesRegions:
        type: array
        description: Liste des régions de l'EPCI
        items:
          type: string
      population:
        type: integer
        description: Population municipale
      surface:
        type: number
        format: float
        description: Surface de l'EPCI, en hectares
      centre:
        type: object
        description: Centre de l'EPCI (Point GeoJSON)
      contour:
        type: object
        description: Contour de l'EPCI (Polygon GeoJSON)
      bbox:
        type: object
        description: Rectangle englobant la commune (Polygon GeoJSON)
  Departement:
    type: object
    properties:
      code:
        type: string
        description: Code du département
      nom:
        type: string
        description: Nom du département
      codeRegion:
        type: string
        description: Code de la région
      region:
        $ref: '#/definitions/Region'
  Region:
    type: object
    properties:
      code:
        type: string
        description: Code de la région
      nom:
        type: string
        description: Nom de la région
